import path from "node:path";
import { writeFile } from "./utils/writeFile.js";
import { loadLanguages } from "./lib/readLanguages.js";

async function main() {
  const DIST_DIR = path.resolve("dist");
  const languages = await loadLanguages();

  // Generate JavaScript file with language data
  const content = `
/**
 * This file is auto-generated by the build script.
 *
 * Do not edit this file manually.
 */
export const languages = ${JSON.stringify(languages, null, 2)};
`.trim();
  writeFile(path.join(DIST_DIR, "languages.js"), content);

  // Generate type definition for the generated file
  const dtsContent = `
import { Language } from "../src/types/language";
export declare const languages: Language[];
`.trim();
  writeFile(path.join(DIST_DIR, "languages.d.ts"), dtsContent);

  console.log(`Successfully generated ${languages.length} languages`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
