import path from "node:path";
import { writeFile } from "../utils/writeFile.js";
import { loadLanguages } from "../lib/loadLanguages.js";

function generateLanguageFiles(data: any, raw: boolean = false) {
  const DIST_DIR = path.resolve("dist");

  const names = {
    file: {
      js: raw ? "languages.raw.js" : "languages.js",
      dts: raw ? "languages.raw.d.ts" : "languages.d.ts"
    },
    var: {
      js: raw ? "rawLanguages" : "languages",
      dts: raw ? "RawLanguage" : "Language"
    }
  };

  const content = `
/**
 * This file is auto-generated by the build script.
 *
 * Do not edit this file manually.
 */
export const ${names.var.js} = ${JSON.stringify(data, null, 2)};
`.trim();
  writeFile(path.join(DIST_DIR, names.file.js), content);

  const dtsContent = `
import { ${names.var.dts} } from "../src/types/language";
export declare const ${names.var.js}: ${names.var.dts}[];
`.trim();
  writeFile(path.join(DIST_DIR, names.file.dts), dtsContent);

  console.log(`Successfully generated ${data.length} ${raw ? "raw " : ""}languages`);
}

function generateLanguageIndexFile() {
  const content = `
/**
 * This file is auto-generated by the build script.
 *
 * Do not edit this file manually.
 */
export { languages } from "./languages.js";
export { rawLanguages } from "./languages.raw.js";
`.trim();
  const DIST_DIR = path.resolve("dist");
  writeFile(path.join(DIST_DIR, "index.js"), content);
  writeFile(path.join(DIST_DIR, "index.d.ts"), content);
}

export async function generateLanguages() {
  const { data, raw } = await loadLanguages();
  generateLanguageFiles(data, false);
  generateLanguageFiles(raw, true);
  generateLanguageIndexFile();
}
