import path from "node:path";

import { writeFile } from "../utils/writeFile.js";
import { loadLanguages } from "./loadLanguages.js";

function generateLanguageFile(data: any) {
  const DIST_DIR = path.resolve("src/languages");

  const names = {
    file: "languages.ts",
    var: "languages"
  };

  const content = `import type { Language } from "../types/language.js";

/**
 * This file is auto-generated by the build script.
 *
 * Do not edit this file manually.
 */
export const ${names.var}: Language[] = ${JSON.stringify(data, null, 2)};
`.trim();
  writeFile(path.join(DIST_DIR, names.file), content);

  console.log(`Successfully generated ${data.length} languages`);
}

export async function generateLanguage() {
  const languages = await loadLanguages();
  generateLanguageFile(languages);
}
